#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

export RNG_PROJECT_DIR=$(pwd)
export RNG_PROJECT_SRC=$GPU_WM_PROJECT_DIR/src



# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Move headers to lnInclude
wmakeLnInclude src

# Compile unittests
wmake $targetType unittest




